[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "@layerzerolabs-lz-evm-protocol-v2/=dependencies/@layerzerolabs-lz-evm-protocol-v2-3.0.139/",
    "@layerzerolabs/lz-evm-protocol-v2/=dependencies/@layerzerolabs-lz-evm-protocol-v2-3.0.139/",
    "@layerzerolabs-oapp-evm-upgradeable/=dependencies/@layerzerolabs-oapp-evm-upgradeable-0.1.2/",
    "@layerzerolabs-oapp-evm/=dependencies/@layerzerolabs-oapp-evm-0.3.2/",
    "@layerzerolabs-oft-evm-upgradeable/=dependencies/@layerzerolabs-oft-evm-upgradeable-3.2.0/",
    "@layerzerolabs-oft-evm/=dependencies/@layerzerolabs-oft-evm-3.2.1/",
    "@layerzerolabs/oapp-evm-upgradeable/=dependencies/@layerzerolabs-oapp-evm-upgradeable-0.1.2/",
    "@layerzerolabs/oapp-evm/=dependencies/@layerzerolabs-oapp-evm-0.3.2/",
    "@layerzerolabs/oft-evm/=dependencies/@layerzerolabs-oft-evm-3.2.1/",
    "@openzeppelin-contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "forge-std/=dependencies/forge-std-1.9.4/src",
]
via-ir = true
optimizer = true
optimizer_runs = 833
verbosity = 2
ffi = true
dynamic_test_linking = true
fs_permissions = [
  { access = "read", path = "script/input.json" },
  { access = "read", path = "out" }
]

[soldeer]
remappings_location = "config"
remappings_generate = true
remappings_version = false

[dependencies]
forge-std = { version = "1.9.4" }
"@openzeppelin-contracts" = { version = "5.1.0" }
"@openzeppelin-contracts-upgradeable" = { version = "5.1.0" }
"@layerzerolabs-oft-evm-upgradeable" = "3.2.0"
"@layerzerolabs-oft-evm" = "3.2.1"
"@layerzerolabs-oapp-evm" = "0.3.2"
"@layerzerolabs-oapp-evm-upgradeable" = "0.1.2"
"@layerzerolabs-lz-evm-protocol-v2" = "3.0.139"

[rpc_endpoints]
mainnet = "wss://mainnet.gateway.tenderly.co"
sepolia = "https://sepolia.gateway.tenderly.co"
katana = "https://rpc.katanarpc.com"
bokuto = "https://rpc-bokuto.katanarpc.com"
polygon = "https://polygon-bor-rpc.publicnode.com"
amoy = "https://polygon-amoy.drpc.org"

[lint]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options